# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 09b5bcc9443fe9ee190859891e251ea5a6bebab9436c1dfd9b890d7876230502ac63940cef8394e09fea7c268fe118e7eaa903b2e7cb2165d25050f315467517

test:
  secret_key_base: 69c51b2fc18a0b013b8d261947c6a53842a76ec35e37526347d94450ed99c56d5176e06800a439705a732d82ff1f1316b056b8ce90d1102dddf1220fd6c72b5c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
